-- CREATE TABLE PRODUTOS(
-- ID_PRODUTO INT PRIMARY KEY NOT NULL,
-- NOME_PRODUTO VARCHAR(100) NOT NULL,
-- DESCRICAO VARCHAR(255),
-- PRECO DECIMAL(10,2),
-- ESTOQUE INT NOT NULL
-- )

-- SELECT * FROM PRODUTOS
-- UPDATE CLIENTES SET NOME='LEMOS' WHERE ID_CLIENTE = 3;
-- UPDATE PRODUTOS SET PRECO=2000.00 WHERE ID_PRODUTO = 1;
-- UPDATE PRODUTOS SET PRECO=2000.00 WHERE ID_PRODUTO = 2;
-- UPDATE PRODUTOS SET PRECO=2000.00 WHERE ID_PRODUTO = 3;

-- DELETE FROM PRODUTOS WHERE ID_PRODUTO=4;
-- DELETE FROM PRODUTOS WHERE ID_PRODUTO=5;
-- DELETE FROM PRODUTOS WHERE ID_PRODUTO=6;

SELECT * FROM PRODUTOS